graph_names_undirected = [
    ## undirected
    "as-caida20071105",
    "as-skitter",
    "actor-collaboration",
    "com-amazon",
    "ca-AstroPh",
    "moreno_names",
    "loc-brightkite_edges",
    "petster-friendships-cat",
    "petster-carnivore",
    # "tntp-ChicagoRegional", listed as undirected in "scale-free networks well done" but it is directed
    "com-dblp",
    "petster-friendships-dog",
    "douban",
    "arenas-email",
    "subelj_euroroad",
    "flickr-links",
    "flickrEdges",
    "flixster",
    "loc-gowalla_edges",
    "petster-friendships-hamster",
    "petster-hamster",
    "hyves",
    "livejournal-links",
    "livemocha",
    "orkut-links",
    "opsahl-powergrid",
    "moreno_propro",
    "reactome",
    "roadNet-CA",
    "roadNet-PA",
    "roadNet-TX",
    "as20000102",
    "wordnet-words",
    "com-youtube",
    "maayan-vidal",
]

graph_names_directed = [
    ## directed
    "moreno_health",
    "advogato",
    "maayan-faa",
    "amazon0601",
    "cit-HepPh",
    "cit-HepTh",
    "zhishi-baidu-internallink",
    "zhishi-baidu-relatedpages",
    "web-BerkStan",
    "moreno_blogs",
    "citeseer",
    "subelj_cora",
    "dblp-cite",
    "eat",
    "ego-gplus",
    "ego-twitter",
    "soc-Epinions1",
    "foldoc",
    "p2p-Gnutella31",
    "web-Google",
    "cfinder-google",
    "zhishi-hudong-internallink",
    "zhishi-hudong-relatedpages",
    "subelj_jdk",
    "subelj_jung-j",
    "libimseti",
    "linux",
    "web-NotreDame",
    "openflights",
    "soc-pokec-relationships",
    "slashdot-zoo",
    "web-Stanford",
    "trec-wt10g",
    "munmun_twitter_social",
    ## "twitter_mpi", huge
    ## "twitter", huge
    "opsahl-usairport",
    "patentcite",
    "wikipedia_link_de",
    ## "wikipedia_link_en", ## too  big
    "wikipedia_link_fr",
    "wikipedia_link_it",
    "wikipedia_link_ja",
    "wikipedia_link_pl",
    "wikipedia_link_pt",
    "wikipedia_link_ru",
    "lasagne-yahoo",
    "maayan-figeys",
    "maayan-Stelzl",
]

graph_names_bipartite = [
    ## bipartite
    "actor-movie",
    "opsahl-collaboration",
    "bookcrossing_full-rating",
    "bookcrossing_rating",
    "dbpedia-country",
    "dblp-author",
    "discogs_affiliation",
    "discogs_genre",
    "discogs_lgenre",
    "flickr-groupmemberships",
    "dbpedia-genre",
    "github",
    "jester1",
    "jester2",
    "livejournal-groupmemberships",
    "dbpedia-location",
    "dbpedia-starring",
    "dbpedia-occupation",
    "orkut-groupmemberships",
    "dbpedia-producer",
    "dbpedia-recordlabel",
    "reuters",
    "gottron-trec",
    "dbtropes-feature",
    "dbpedia-team",
    "pics_ti",
    "pics_ut",
    "pics_ui",
    "trackers-trackers",
    "dbpedia-writer",
    "youtube-groupmemberships",
]

graph_names = graph_names_undirected + graph_names_directed + graph_names_bipartite
